#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

#updating and installing Nginx
sudo apt-get update
sudo apt-get install -y nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
# Create the document root directory and index.html file
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
     listen      80;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restarts the Nginx service to apply the configuration changes.
service nginx -s reload
