#!/usr/bin/env bash
#Bash script that gives information about the school file

if [ -e "school" ]; then
	echo "school file exists"

	#check if file is empty
	if [ -s "school" ]; then
		echo "school file is not empty"

		#check if the file is a regular file
		if [ -f "school" ]; then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi	
